name: Continuous Integration

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  code-analysis:
    name: Code Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install npm
        run: npm install

      - name: Validate code
        run: make validate
